export const SEARCH_CITY = "SEARCH_CITY";
export const SEARCH_CITY_SUCCESS = "SEARCH_CITY_SUCCESS";
export const SEARCH_CITY_ERROR = "SEARCH_CITY_ERROR";
export const FETCH_FORECAST = "FETCH_FORECAST";
export const FETCH_FORECAST_SUCCESS = "FETCH_FORECAST_SUCCESS";
export const FETCH_FORECAST_ERROR = "FETCH_FORECAST_ERROR";
